### ISSUE TITLE
store into a variable, instead of writing it in each factory

### ISSUE THREAD

**Issue by aric87** [mse2321/countries_capitals#9]
https://github.com/mse2321/countries_capitals/blob/master/index.html#L217

**Comment by mse2321** [comment]
Where should this variable go?

**Comment by aric87** [comment]
it can go anywhere outside the factories. There's a way to set a variable on the provider, that would be a good way.

**Comment by aric87** [comment]
http://stackoverflow.com/a/27572809

**Comment by mse2321** [comment]
Done
